# Generated by Django 5.2.2 on 2025-06-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_alter_customuser_location_offer_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
