# Generated by Django 5.2.2 on 2025-06-30 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='linked_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='core.request'),
        ),
    ]
