# Generated by Django 5.2.2 on 2025-06-30 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_offer_linked_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='linked_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.request'),
        ),
    ]
